### ISSUE TITLE
Proposal: shorter dialogue tag syntax

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#1011]
Since all dialogue tags require `type`, we could follow HTML/XML and use it as the "header" of the tag:

```
[color value:red]
[image id:box/scale:2]
```

**Comment by rilifon** [comment]
Cool! I think I can easily make this next meetup

Em qua, 17 de abr de 2019 16:30, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:
