### ISSUE TITLE
Reduce code line length by using auxiliary variable

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#1017]
In `view/sector.lua`, [around line 530](https://github.com/uspgamedev/backdoor/blob/dev/game/view/sector.lua#L350)

See #1016 for more information.

**Comment by OrenjiAkira** [comment]
Code quality should not be a separate issue if one can help it. It should be done with every single PR, otherwise PRs are useless. You could just write dumb ridiculous code and merge it and open infinite issues for "fixing it later". That's not good practice, and it quickly becomes a snowball

**Comment by OrenjiAkira** [comment]
We have discussed this matter personally and agreed that this was done as an exception, although we still see refactoring practices somewhat differently.

**Comment by rilifon** [comment]
Closed by #1019
