### ISSUE TITLE
Profile and saves randomly corrupt themselves, and makes game unplayable

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#118]
I assume it has to do with the game crashing when loading or creating a save. Not sure how to resolve it, though.

**Comment by Kazuo256** [comment]
There are two things that can be done:

1. Use a versioning system for save files. This helps detect when a save file format is too old to be loaded. See #88.
2. Fail more gracefully when a save file can't be loaded, like warning the player and proposing that the saves be removed.
