### ISSUE TITLE
How to avoid making so many borders for every tile type?

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#131]
This is a discussion that came up at #125. Here are the first solutions I can think of (not particularly good ones):

1. Don't use borders at all
2. Make the image larger than a single tile, so that it "overflows" to the sides naturally
3. Use [wang tiles](http://procworld.blogspot.ca/2013/01/introduction-to-wang-tiles.html)
4. For walls, we could make 3D models to generate the sprites, we only need the texture

**Comment by OrenjiAkira** [comment]
I have some questions:

+ Not using borders seems... hard. I cannot think of how it would look any good this way. Not in the resolution we've chosen, with isometric perspective. If we can find good visual reference, that'd be cool.
+ I am down with making larger images so they overlap nicely. **In theory** it sounds great. 
+ I need to understand how to make these wang tiles. They sound good, but I am having trouble picturing actually making them.
+ I hate that idea. That does not work for isometric pixel art. Unless we make the whole thing using 3d models, it'll look silly and go right into the uncanny valley (as in overproduced when compared to the rest of the sprites)

**Comment by OrenjiAkira** [comment]
I have some questions:

+ Not using borders seems... hard. I cannot think of how it would look any good this way. Not in the resolution we've chosen, with isometric perspective. If we can find good visual reference, that'd be cool.
+ I am down with making larger images so they overlap nicely. **In theory** it sounds great. 
+ I need to understand how to make these wang tiles. They sound good, but I am having trouble picturing actually making them.
+ I hate that 3d idea. That does not work for isometric pixel art. Unless we make the whole thing using 3d models, it'll look silly and go right into the uncanny valley (as in overproduced when compared to the rest of the sprites)

**Comment by OrenjiAkira** [comment]
Sorry, stupid mobile typing interface made me accidentally close the issue

**Comment by Kazuo256** [comment]
It seems you also double-posted XD.

I'm OK with option 2 (I edited the original text to number each option). It seems the simplest that can get the job done. But it only works for floor tiles, so I gather we'll stick to 8-border walls?

**Comment by OrenjiAkira** [comment]
Well, walls are much more easily done. They are mostly just their tops anyway. We _could_ go back to using just one tile for the wall, but we'd have to solve visibility for things behind it without making them look weird.

**Comment by Kazuo256** [comment]
I like the current way walls look, if it is not too much trouble for you XD.

**Comment by OrenjiAkira** [comment]
Nah. Walls are basically copy-pasting and flipping stuff. Wang tiles would be good for some randomness in their pattern though.

**Comment by Kazuo256** [comment]
Good, then I'm closing this issue, since we got our answer. I'll open an issue to test out the new tiles.
