### ISSUE TITLE
Draw health bars on top of bodies

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#153]
Add to `MapView:draw()` on `game/domain/view/mapview.lua` the rendering of health bars on top of each body. Each bar is composed of two rectangles: a dark bakground, and a green foreground whose width is proportional to the health percentage.

Optionally, the foreground bar can change shades do yellow then red as the body's health lowers.

**Comment by Kazuo256** [comment]
@camilainetti 
How's work on this? I see you've made a branch and it seems to be done already. Can we merge it?

**Comment by rilifon** [comment]
@camilainetti bump

**Comment by OrenjiAkira** [comment]
closed via  4c28b4e

**Comment by rilifon** [comment]
hurraaay
