### ISSUE TITLE
Start game at resolution specified in profile

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#1590]
Instead of changing it after starting.

**Comment by rilifon** [comment]
This seems unfixable for now. Love2D reads the start resolution parameter from the conf.lua, before loading any modules, and at the current love version, we can't write from files that are beyond the save directory. So the only "solution" would be creating a script to exclusively run the game, that modifies the conf.lua file from source/.love file before loading the game, using information from the profile file, which is located in the players save directory, that differs in location for each OS...

Our solution to circumvent the problem will be to start the game at windowed mode everything (already done) and start at a splash screen, changing to the desired resolution afterwards. Created issue #1600 for this

Closing this issue for now with the label 'wontfix', but if any discoveries about this issue surfaces, we can reopen it. Also there is an open branch of my attempts to fix this (creating a conf.lua in save directory hoping LOVE would override the default one) but to no avail. The branch is at https://github.com/uspgamedev/backdoor/tree/fix/1590, but we'll probably delete it in the near future.
