### ISSUE TITLE
Action format

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#160]
We need a way to represent actions. Initial suggestion:

Actions have three lists: parameters, values, and effects.

1. Parameters are used to receive input from actors (their behaviors actually)
2. Intermediate values computed for the effects
3. The actual effects of the action

Example:
```lua
action = {
  params = {
    { "choose_target", {5, "BODY"}, "target" } -- body-only target within range 5
  },
  values = {
    { "get_attribute", {"ATH"}, "attr" }, -- gets actor attribute
    { "add", {"attr", 3}, "amount" }, -- sums results from value "attr" with constant (3)
  },
  effects = {
    { "deal_damage", { "val:amount", "par:target" } } -- deals ATH+3 damage to target body
  }
}
```

**Comment by rilifon** [comment]
Interesting, but can we make really complex actions just using this method? What other kinds of different operators have you thought about?

**Comment by Kazuo256** [comment]
> Interesting, but can we make really complex actions just using this method?

I think so. At least, much more complex than we'll be needing for a long time. The format is almost equivalent to funcional programming, except it does not support recursion.

> What other kinds of different operators have you thought about?

A quick brainstorm:

+ Getters for actor and body attributes in general
+ Math operations
+ Relational operations
+ Multiplexors and step-conditionals (return 1 when condition is true)
+ Map-related finders: nearby bodies, bodies in-between, etc.
+ Dice values (1d6, 3d8, etc.)

But I believe the most important factor will be the effects, not the operators.

**Comment by Kazuo256** [comment]
Made some changes to the syntax from @marcheing's suggestions. Basically, instead of referring to values by index, we give them names. This allows us to differentiate between constants and referenced values, besides directly referencing to parameters.
