### ISSUE TITLE
Store sector specs in database the same way as bodies and actors

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#165]
Bodies and actors each have a single JSON file in the database containing the entires for every spec in the corresponding domain. On the other hand, sector specs are currently stored on separate, individual files. Since the `database` module was designed for the former usage, it would be best if sectors followed the same storage structure.

**Comment by OrenjiAkira** [comment]
Ohhh, now I get it. That's easily fixable.

**Comment by OrenjiAkira** [comment]
should we organize sector-generation by name or by index?
