### ISSUE TITLE
Achievement Cards

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#190]
Cards that make permanent upgrades to actors.

**Comment by rilifon** [comment]
Technically they will be exactly as the Habitus, but will only use effects that permanently change the actor attributes right?

If so we can program them just as Habitus cards and add to our list some effects that do this, or do you want some actual restriction so even on the devmode you can only create cards using effects that can do this? Or this restriction will be solely on our responsability so we don't create a habitus card that has an effect that doesn't fit its purpose?

**Comment by Kazuo256** [comment]
I think I can make the devmode only show effects appropriate to the card type, but underneath they all just behave like habitus arts.

Guess it makes sense to make use of the effect system. MTG card types could probably all be "implemented" as sorceries XD.

**Comment by rilifon** [comment]
I think initially that was their idea since monster cards were "summon X" hahah

**Comment by rilifon** [comment]
Ok, anyway, there is still an issue we have to consider. In the game we are working directly with the specs, getting and using their values for stuff. So for the achievements cards to work they are must change the specs value, but that will change the default value for stuff =(

**Comment by rilifon** [comment]
I think the best solution should be actors having a variable for each attrbute modifier, such as ath_mod, and the getAth() for instance return the spec + correspoding modifier

**Comment by Kazuo256** [comment]
I was going to answer exactly that. In fact, @OrenjiAkira and I were discussing this same solution yesterday =D.

We also discussed how to handle *temporary* modifiers, which requires a little more code but is still simple.

**Comment by rilifon** [comment]
just edited my comment realted to that hahah
