### ISSUE TITLE
Rename `RANDOM` module to something better

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#219]
I was thinking of renaming it to `RNG`. This way, we can rename the function `interval` to just `random` or `getRandom`. Also we could name other methods like `odd` or `even` like `getRandomOdd` or `getRandomEven`.

This might help in terms of intuitiveness for the team, maybe? I want to know what y'all think.

**Comment by rilifon** [comment]
both RANDOM and RNG seems ok for me. I guess I don't really like the 'interval' name for the function, but I don't mind if it stays the same (getRandom() or just generate() seems more appropriate for me I guess). But I think all of this are really minor issues,  I doesn't bother me at all the way things are right now

**Comment by OrenjiAkira** [comment]
Well, the standard equivalent for what the current `interval` function is usually named `random`, so I thought that callind `RANDOM.random()` would be...uhh, weird. `generate` sounds like a much better option.

**Comment by Kazuo256** [comment]
Another option for `generate` is `next` or `getNext`. But I also don't mind either.

**Comment by OrenjiAkira** [comment]
Ok, so I will soon refactor it to `generate` then.
For consistency I plan on renaming `odd` and `even` to `generateOdd` and `generateEven`.
