### ISSUE TITLE
Compress savedata

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#222]
Saves at this moment can easily become more than 1MB in size. Compressed in zip format, those same save files become 8~12kB (that's like 99% compression!). I think LOVE2D has a function for mounting/unmounting directories? We should check it out sometime.

**Comment by OrenjiAkira** [comment]
Ok, so LOVE2D's mount/unmount only works for preexistent `.zip` files. It can only extract and undo extracting, but it cannot create new `zip` files. We'll have to find something else, probably a external lib.

Unless someone's planning on implementing their own thing.

**Comment by Kazuo256** [comment]
https://luarocks.org/modules/brimworks/lua-zip

And it seems to be löve-compatible, though I don't know what that even means.

**Comment by rilifon** [comment]
I don't like the ideia of using external libs that need to modify the LOVE since it will make game distribution a lot harder ><
I'm looking for some articles or repositories related to compressing our save files and there isn't a lot available for love, but I found this neat LZW compression in lua:
https://github.com/Rochet2/lualzw

I will try to implement it and run some tests to see if it can reduce significantly our data usage. If so I will create a pull request and if aproved  by you guys, @Kazuo256 can later add the repository to our Makefile

**Comment by rilifon** [comment]
Also in the future I really wanted to make my own LZW since I never programmed anything liked it and it seems something really cool to make it yourself once in a lifetime haha

**Comment by Kazuo256** [comment]
> I don't like the ideia of using external libs that need to modify the LOVE since it will make game
> distribution a lot harder ><

The lua-zip module doesn't require modifying LÖVE, it just has to be used as a dynamic library. The distribution does get slightly messier, but not much more than it already will be.

**Comment by OrenjiAkira** [comment]
I dislike using anything compiled further from love-imgui. love-imgui can easily be deactivated for non-debug distributions without any consequences, but adding further external compiled libs will make distribution harder

**Comment by Kazuo256** [comment]
Fair enough. Since I've already had the "once in a lifetime" opportunity of writing a compression algorithm, I'll leave the fun to you guys =P.

**Comment by OrenjiAkira** [comment]
...using lua

sounds fun
and painful

**Comment by OrenjiAkira** [comment]
i have found and tested this:

https://github.com/Rochet2/lualzw

it compressed stuff 4-6 times bigger than `zip` does. a similar savefile of 42kB became 6.5kB with `lualzw`, but only 1.5kB with `zip`

**Comment by rilifon** [comment]
Tried here as well. I think for now this is a really good measure, and we can search for better alternatives in the future if we feel like the saves are still occupying too much space. What do you guys think?

**Comment by Kazuo256** [comment]
Seems fine to me.

**Comment by OrenjiAkira** [comment]
so we use `lualzw`? I have a stable branch for pushing.
