### ISSUE TITLE
Add Attributes Temporary Modifier and Effects

### ISSUE THREAD

**Issue by rilifon** [uspgamedev/backdoor#244]
Think a clever way to implement temporary modifiers to attributes, and create effects to apply them

 My idea:

Temporary attributes affect directly the attrib modifier variable, but the actor stores "timers" or "clocks" that indicates changes in future turns, using countdowns. For example, giving a +3 to ATH for 10 turns would increase the ath_mod variable by 3, but the actor receives a static effect "reduce ATH by 3" with a countdown for 10 turns.

The game will update all countdown effects in the beguinning of the actor turn, and check if anyone has reached 0. If so, apply the effect.

Opinions?

**Comment by Kazuo256** [comment]
Another way to do this would be to store the modifiers in a list (and there would be a list for each attribute). Each time we inspect a certain attribute, we iterate over the corresponding list adding the values before adding it to the final result. Timers can also be used to remove the modifiers when appropriate.

Advantage: allows us to know where each modifier value comes from all the time.

Disadvantage: more costly to compute, but I really don't think it's going to be a problem.

Another problem is when we have modifiers that are not additive, but multiplicative (or any other operation). The idea we had yesterday involved using different lists of modifiers for each kind of modification, plus providing different methods of combining them (addition, multiplication, etc.).

**Comment by rilifon** [comment]
Serious proposition: Use MTG layer 7 model to our modifiers

It really complements your idea of using a modifiers list, and we could use it like a queue, similar to the timestamp mechanic, everytime we need to get an attribute from an actor, applying the temporary attributes in order. As you mentioned is a bit more costly to compute, but pretty sure its irrelevant

**Comment by rilifon** [comment]
if we padronise our own "layer system" we could have each layer a specific list and apply them in order!

**Comment by Kazuo256** [comment]
I'll have to read how the layer system works. Never done that before >.<

**Comment by rilifon** [comment]
Actually the idea is pretty simples, just classify types of modifiers and apply them in order.
Magic has a more specific distribution in layer 7, since its the one relative to power/toughness and the game have lots of mechanics to influnce them.

So, everytime the game needs to use an attribute value he follows this order:

1 - Get the spec value of the actor.
2 - Apply all modifiers, in order they were received, that "set the attribute" (e.g. "Effect: Set actor ATH to 3 for 4 turns")
3 - Apply all modifiers, in order they were received, that "increase or decrease attribute value, but does not set" (e.g. "Effect: increase actor ATH by 5")

**Comment by OrenjiAkira** [comment]
`in order they were received` is kinda complicated in MTG. Like, if there is a mult modifier, given AFTER a plus modifier, then it would make a difference as in: `(base + plus) * mult`, as opposed to `base * mult + plus`. Do we want to preserve order, or is the order based on the `type` of modifier?

**Comment by rilifon** [comment]
MTG usually doesn't have multipliers, but they all are `in order they were received`. I believe we could add a 4th layer that applies multiplication modifiers.

**Comment by rilifon** [comment]
also this are all for continued effects that last for a period of time, not instant effects, such as "deal damage to enemy equal to ATH + 3 or 2*ATH. In that case both of these changes (+3 or *2) would only be applied after the calculation of the ATH based on the layer system

**Comment by Kazuo256** [comment]
I see. Let me try to simplify the situation:

If we stick to additions and multiplications, a fixed order of operations suffices.

If, however, we allow modifiers such as "set the attribute to X", then we NEED the timestamp mechanism.

**Comment by OrenjiAkira** [comment]
yeah, i mean, we are talking about what the `getATTRIBUTE` method should return, right? not what the effect will do with it after, that's a whole different thing.

also, isn't MTG based in stacks? so wouldn't the modifiers work in reverse order?

**Comment by rilifon** [comment]
The layer system has the upside to not cause ambiguity when applying multiple continuous effects on the same variable. I think is a pretty solid design solution for the problem, we just need to settle on a particular order to apply the effects, but I think this one I recommended, based on the MTG Power/Toughness layer order is pretty solid
but we could add a 4th layer regarding multipliation or waht not, but I prefer these types of effects be created like i mentioned above, directly on the spell and applied after the calculation

**Comment by rilifon** [comment]
Pretty much what @Kazuo256 said. Also, continuous effects on MTG are one of the few things that uses a queue instead of stack, for obvious reasons (if you cast a "set power to 2 in a monster, using the stack design would make other "set attribute" effect useless)

**Comment by rilifon** [comment]
Shouldn't the modifiers be a tuple so we can remove temporary effects? Or are we planning on using the timers separately to remove the modifiers when the effect ends?

Also, yes, the timestamp is basically a FIFO order, it should be any problem to implement. MTG timestamp is a bit more complicated since eveytime something references and effect or elemtn on the game its timestamp refreshes, but I don't think we need to do this for our game (for now anyway xP)

**Comment by Kazuo256** [comment]
> Shouldn't the modifiers be a tuple so we can remove temporary effects? Or are we planning on using the timers separately to remove the modifiers when the effect ends?

Since there might be modifiers that are not based on time, I think it's best if we handle their duration somewhere else in the Actor class.

**Comment by rilifon** [comment]
But I think we just need two list then. One for effects that set, and another for operations. I don't think wee should separate multiplication from addition. I believe we can leave the player to figure it out the strategy of using "add" effects before "multiplication"

**Comment by Kazuo256** [comment]
> But I think we just need two list then. One for effects that set, and another for operations. I don't think wee should separate multiplication from addition. I believe we can leave the player to figure it out the strategy of using "add" effects before "multiplication"

If all lists use timestamp, why not just one list then?

**Comment by rilifon** [comment]
> If all lists use timestamp, why not just one list then?

But then don't use at all layers?

**Comment by Kazuo256** [comment]
I don't know the other layers. What would that mean?

**Comment by rilifon** [comment]
Oh, just the "Set Attribute" layer and the "Other modifiers" layer, such as adding or multiplying the value

**Comment by Kazuo256** [comment]
The "Other modifiers" layer also works by timestamp or is it by predetermined order?

**Comment by rilifon** [comment]
both have their own timestamp. Basically they are two queues and we apply the first queue first

**Comment by Kazuo256** [comment]
Oh, right. That way you +X bonuses stick even if you get a "set to Y" modifier. Seems good.
