### ISSUE TITLE
Input hold vs. toggle

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#250]
Right now, widgets selection uses hold and card selection uses toggle.

Let's think about each of them and choose a consistent way of handling this kind of input.

**Comment by OrenjiAkira** [comment]
i think cards should be hold too

**Comment by Kazuo256** [comment]
I like the feel of hold, but the confirming part is still a bit awkward. You end up with two buttons down (the hold and the confirm) and either you snap them up hurriedly or keep holding both for a while (and weird things might happen). Not sure I managed to explain properly.

**Comment by Kazuo256** [comment]
An alternate way woud be that releasing the hold confirms the selection, but that seems too prone to accidents.

**Comment by OrenjiAkira** [comment]
I was gonna say the same thing about hold and release!

But like, I feel like the problem is the widgets and not the cards? Like, you **want** a card menu, to look at and think and do things. The widgets, which are more fast paced, are the problem. They need a fast paced thing, for a multiple option thing, and that is hard to be fast without being prone to accidents?

**Comment by Kazuo256** [comment]
I see. Guess we can try the hold&release confirmation mechanism for widgets.

What about the cards then?

**Comment by OrenjiAkira** [comment]
I guess I take it back and the cards can be a traditional menu, with press commands only.

But we need to think properly about this whole input/action thing. I think there are quite a few actions the player can make at any given moment. I feel like we need to map them properly to inputs and states, and make sure we are all on the same page about it too. That will help design the interface in a more consistent and palatable thing.

**Comment by Kazuo256** [comment]
Yeah. How about we discuss that next meeting?

Let's also wait to see of @rilifon has anything to say regarding this issue in particular.
