### ISSUE TITLE
Add races/backgrounds to database

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#258]
I was making a simple DB entry for races but I wanted to make sure how we're going to do this.

I was thinking of a race/background entry being among the lines of:
```json
{
  "race_name": {
    "bodyspec": "bodyspecname",
    "description": "Long text describing some lore.",
  }
}
```
(substitute body for actor in background entries)

This makes the description something related only to the background/race, and not the actor/body. If we want to show actual number specs on them, we can just get them from the corresponing actor/body given that we have the specname.

**Comment by Kazuo256** [comment]
I've been thinking about these many configurable things we want to put into the DB (not only races and backgrounds but also others constants, flags, and general data-driven values) that are not exactly a domain per se (like bodies and actors). Ideally, there should be some dedicated DB tables for them, which do not assume there is a "collection" of entries, but "specific" entries.

In this case in particular, if we move the description field to the body and actor domains, there could simply be a DB table "Player Settings" (or something like that) with a field "playable races" and another "playable backgrounds". With this, we wouldn't be able to use `DB.loadDomain` or `DB.loadSpec`, but rather we'd need something like `DB.loadSetting` (or similar).

In concrete terms there would be a `database/settings/player.json` looking something like:

```json
{
  "playable_races": [ "hearthborn", "ironborn", "burrowborn", "stormborn" ],
  "playable_backgrounds": [ "fighter", "caster", "crafter" ]
}
```

And the code used to load it:

```lua
local playable_races = DB.loadSetting('player', 'playable_races')
```

Hopefully this is easier than trying to adapt the domain-based part of the DB.

But I'm not 100% sure of this approach either.

Also, I'm not 100% sure about using the term "races" either XD. Wouldn't "species" be more accurate?

**Comment by OrenjiAkira** [comment]
Well, that requires refactoring and by so it is not strictly easier. I guess it's a few tweaks on `database/init.lua` plus directory addresses on the devmode code? I don't know how hardcoded that is.

Also if there is going to be a distinction of things that are not domains, then it'd be nice if those files were also inside a separate directory. Like so:
```
game/database/
..domains/
....actor.json
....body.json
....[...]
..settings/
....player.json
```

**Comment by OrenjiAkira** [comment]
Also, what about the schemas? Would they stay in the same place, the way they are?

**Comment by OrenjiAkira** [comment]
@Kazuo256 I have made this branch: [example/species-background](https://github.com/uspgamedev/backdoor/tree/example/species-background)
It uses domain still, but can it easily be refactored to using this code you proposed?

**Comment by Kazuo256** [comment]
> Also if there is going to be a distinction of things that are not domains, then it'd be nice if those files were also inside a separate directory.

Sounds nice!

> Also, what about the schemas? Would they stay in the same place, the way they are?

I'm thinking of moving them all to their respective class files. Actors' schema would be in `game/domain/actor.lua`, for instance.

> It uses domain still, but can it easily be refactored to using this code you proposed?

The shortest path would be to keep using domains, but make a new single domain called "player-settings" or something, with the table layout I described. We can open another issue for separating domains from settings. The problem is that devmode would not be able to edit it as it does now, but I'd say that is beyond the scope of the issue anyway (in other words, we can add devmode support later too).
