### ISSUE TITLE
Rename "HUDl" to something clearer

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#279]
I suggest "HUD_BG"

**Comment by OrenjiAkira** [comment]
On a tangent, I would suggest that whatever code the layers use to draw should have an ordering factor, like a z-index, but i think that's steaminglib's code.

I'm also fine with using numbers for layers of the same "kind" like, L1 L2, HUD1, HUD2, so long as it's consistent

**Comment by rilifon** [comment]
The ideia of layers is not caring about the order inside them.

HUD_BG seems a good name, in other projects I was using l and u for indicanting layers above or below acertain layer (to specify layer just made to create effects or filters above or below a certain layer).

I thin kwe can use BG for background and FG(?) for foreground in layers when we want to apply effects.

Also, yes, we still aren't using the L2 layer, but I think we will as soon as we have animations running ^^
