### ISSUE TITLE
Simple map tiles: "Ruins"

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#28]
With transition parts
- [x] Cobblestone tiles
- [x] Dirt tiles
- [x] Walls

**Comment by Kazuo256** [comment]
Some references:

![Reference 1](https://s-media-cache-ak0.pinimg.com/236x/9d/ff/55/9dff55c2281898d40b2e349a235d4dcc.jpg)

![Reference 2](http://images.geeknative.com.s3.amazonaws.com/wp-content/uploads/2014/06/Jonas-De-Ro-3.jpg)

![Reference 3](http://cdn.paper4pc.com/images/fantasy-art-abstract-apocalyptic-ruins-dark-wallpaper-1.jpg)

Anyone fell free to add more references.

**Comment by OrenjiAkira** [comment]
Let's clarify that this issue simply means to "make the sprites", even if just for testing purposes. Testing and further fixing will have to be another issue when it comes to it.
