### ISSUE TITLE
Reset Saves

### ISSUE THREAD

**Issue by rilifon** [uspgamedev/backdoor#284]
Creating something to easily delete all savedata from our game, including profiles, so we have a quicker way to reset our saves.

Options I thought about: 
a button that deletes all files and closes the game; or
and argument when running the game that deletes the savefiles before setting stuff up

**Comment by Kazuo256** [comment]
> and argument when running the game that deletes the savefiles before setting stuff up

Already done in #177. Just run with:

```bash
make FLAGS=--clear
```

**Comment by OrenjiAkira** [comment]
Can I close this?

**Comment by Kazuo256** [comment]
Let @rilifon do it so we know he's read it.

**Comment by rilifon** [comment]
uuuhh nice!

We should add what flags are available when running the game in the README or somewhere else for easy access ^^
