### ISSUE TITLE
Memory usage fluctuates a LOT

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#287]
Exploring around I have noticed love's memory usage to fluctuate from 300MB to up to 1+GB! It causes eventual lags, **both mid-sector (walking around) _and_ between sectors (loading new sectors),** so I can't pinpoint the cause. The strangest thing is that it goes up and down with a variance of 700MB! (And possibly more!) That's a lot to free and allocate on the get-go. What the hell are we doing that consumes so much memory?

**Comment by Kazuo256** [comment]
@rilifon said something today about the game lagging on his notebook sometimes when moving too fast. Might be related.

**Comment by OrenjiAkira** [comment]
I noticed that sometimes, leaving the game be for a while, it gradually increases the mem usage. It got up to 2GB last time.

**Comment by Kazuo256** [comment]
Did a few quick tests here and the memory had no spikes like those. Will test more extensively at a later time.

**Comment by rilifon** [comment]
Wow that really weird. I had some lagging issues on my notebook whenever I walked a lot in the main map and kept changing buffers non-stop on the drawcard menu.

I will run some tests here as well and report anything I find

**Comment by OrenjiAkira** [comment]
Tested calling `collectgarbage` every 16 frames and it made the memory usage stay consistently under 100MB.

Also this indeed seems to be platform specific, probably (macOSX for sure)

**Comment by OrenjiAkira** [comment]
Anyone still having issues with this? I'm not.

**Comment by Kazuo256** [comment]
Never had =D

**Comment by rilifon** [comment]
Closing this
