### ISSUE TITLE
Upgrade cards

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#30]
+ [x] A vanilla upgrade card
+ [x] A static effect upgrade card
+ [x] A trigger effect upgrade card

**Comment by dread-uo** [comment]
What would static effect upgrade and trigger effect upgrade cards be?

**Comment by Kazuo256** [comment]
Static effects are continuous effects, like "you get movement speed +2". They remain valid as long as the upgrade is installed.

Trigger effects are conditionally-timed effects, like "whenever you hit a monster, draw a card".
