### ISSUE TITLE
Improve information on buffers when selecting them

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#301]
Right now it's really hard to tell which buffer is which, how big it is, and how much there is in the discard stack. I'd suggest organizing this info vertically, as in:

```
label1: value1
label2: value2
```

I'm sure our interface things are provisory atm, but they should be enough for the dev team (and potential new dev team members) to understand them as well.

**Comment by Kazuo256** [comment]
Is this about the interface for choosing buffers to draw from, or the one used to choose pack cards to assign to buffers?

**Comment by OrenjiAkira** [comment]
The one we draw cards from.

**Comment by OrenjiAkira** [comment]
Buuuuuut! This should apply to the packdraw one too, for the same reasons. But that'd be a separate issue, when I merge it.

**Comment by Kazuo256** [comment]
Closed because of #369
