### ISSUE TITLE
Maybe we should refactor params/effects/operators to inherit from classes?

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#302]
All that repeated code bugs me. But they are so smol, it's not that bothersome either. I don't know. Should we?

**Comment by Kazuo256** [comment]
How would inheritance reduce repeated code?

**Comment by OrenjiAkira** [comment]
All params and operators have a single schema item, for instance, that says:
```lua
{ id = "output", name = "Label", type = "output"}
```
Many params have empty validators that just `return true` as well.
Also the function's arguments would be documented more properly and that would help us avoid typing them out of order and such.

Not sure if inheritance is the word, but like, a prototype? A template? Something that serves the purpose of kickstarting the creation of a new one.

**Comment by OrenjiAkira** [comment]
Again, not sure if an actual issue, because they are so tiny.

**Comment by OrenjiAkira** [comment]
I think just metatables would solve this, partly
