### ISSUE TITLE
Effect animations system

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#322]
Based on what we've done for #134 (also see #319), we need to implement a way to handle the many effect animations that can happen flexibly enough.

Right now, ti somewhat works like this: effects can yield the turnloop routine to request a "report", that is, presenting something about the effect to the user. Then, the gamestate locks until the corresponding animation is finished. Currently, this is forwarded directly to SectorView, but we need a proper object to manage this. I was thinking of making a `VFXPlayer` class-thing somewhere in `game/view`. Not sure how it will communicate with all the views yet.

Also, it would be good to allow non-blocking animations too.

Here's a quick brainstorm of animations we might have on the game:
+ Particle splatter
+ Bullets
+ Lasers
+ Damage popups
+ Status popups
+ Card animations (draw hand, consume, remember, open pack...)
+ Sprite-based effects (RPGMaker style)
+ Etc.

**Comment by rilifon** [comment]
> Sprite-based effects (RPGMaker style)
Can you link an example for this?

We can work on this next meeting, how about that? =)

**Comment by Kazuo256** [comment]
>>Sprite-based effects (RPGMaker style)
>
>Can you link an example for this?

[Like this](https://opengameart.org/content/explosion)

**Comment by rilifon** [comment]
We should break this issue into smaller issues (also because we have made several itens from it), since its too general

**Comment by Kazuo256** [comment]
Closing and divinding into finer grained issues:
#711 
#712
#713
#715
#716
#372
