### ISSUE TITLE
Adapt healthbar height to body sprite

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#331]

**Comment by OrenjiAkira** [comment]
how about using the appearance to store height?

**Comment by Kazuo256** [comment]
Hum. Seems good.

**Comment by rilifon** [comment]
If we could retrieve the sprite from a body (if this doesn't break the MVC model), we can just get the current sprite height and draw the healthbar accordingly.

Although this would make de healthbar wiggle around if the sprite has a ever-changing height idle animation and I can't picture if this would be a cool effect or just annoying haha

**Comment by OrenjiAkira** [comment]
This is why I suggested putting the value on the `appearance` entry. This would set the height to a set value for all related sprites and animations of that set of animations

**Comment by Kazuo256** [comment]
Closed thanks to new health bar
