### ISSUE TITLE
Allow full block damage?

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#356]
Question introduced while implementing #355.

Should defense reduce damage all the way to zero? Or should it allow at least 1 damage point to pass no matter what? (immunity mechanics aside)

Reducing to zero might make the experience too frustrating if it's too hard to cause any damage, while reducing to 1 means you cannot ever avoid taking damage through normal means.

**Comment by OrenjiAkira** [comment]
> [...] all teh way [...]
"hOi im temmie! shud wee awow defens all teh wae to zero? hOi hOi"

**Comment by Kazuo256** [comment]
¬¬

**Comment by Kazuo256** [comment]
Deprecated by #799
