### ISSUE TITLE
Feature proposal: attribute aptitude

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#366]
Just a crazy idea to think in the future.

Actor specs can have an "attribute aptitude" instead of "attribute base", and actor states have "attribute experience", making the actual attribute value something like "experience/aptitude". This stops players from making muscular mages or barbarian geniuses (which is debatably undesirable).

It also allows all actors to start with the same "base attributes", and it naturally adjusts to their aptitudes. For instance, all actors could start with 100 "attribute experience" on all attributes, and actors with aptitude 10 would have a grater starting value than actors with aptitude 20 (we could invert the values when showing the player for clarity).

Anyway, not sure if this will be any good. Let's wait until we have a proper environment for playtesting.

**Comment by rilifon** [comment]
Really liked the flavor it brings to characters. I think we should test it out when possible!
