### ISSUE TITLE
THE GREAT RETCON

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#369]
So.

Talking to @OrenjiAkira and realizing how everything's become very difficult to manage (or is it?), we formulated a HUGE AND CRUEL SIMPLIFICATION of the game as follows:

1. Actors only have ONE buffer
2. Using cards puts them on the DISCARD PILE instead of destroying them
3. You can only consume cards directly from your discard pile
4. Opening a pack directly puts all opened cards in the discard pile

Consequences:

1. Drawing a hand becomes trivial
2. Opening packs becomes trivial
3. Since cards are no longer destroyed by use, there's no need for infinite basic packs
4. We can have a menu option "Consume", which is the only way to get rid of cards

What do you think, @rilifon?

**Comment by marcheing** [comment]
What is happening!?

**Comment by Kazuo256** [comment]
We are going crazy is what is happining.

**Comment by rilifon** [comment]
I need to ponder this while sipping from dark tea. I will bring my thoughts in the near future. May God have mercy on our souls.

**Comment by Kazuo256** [comment]
Is it alright to close this by now?

The only thing we haven't adopted is the simplification of opening packs, since, as @rilifon argued, it makes things easier for the player. Other than that, we just don't have non-basic packs, but that is something we would do anyway.
