### ISSUE TITLE
Three actual monsters

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#376]
Accepting ideas.

**Comment by rilifon** [comment]
Omar, the Destroyer.


But for reals, I think is better to think of monsters if you provide some documents or related material to your universe for inspirarion
(leaks for first chapters yay or nay?)

**Comment by OrenjiAkira** [comment]
I have three easy to add monsters soon to be done

**Comment by OrenjiAkira** [comment]
But we def could have an omar newbie killer chara too. It should be a humanoid dog

**Comment by rilifon** [comment]
or a cone

**Comment by Rewasvat** [comment]
I SAW THAT!

Just a dog, no furries please. Maybe with sea-related powers? Just brainstorming.

**Comment by Kazuo256** [comment]
> Just a dog, no furries please

How to dig your own grave.

**Comment by OrenjiAkira** [comment]
honey u are def getting ur fursona in the game now

**Comment by OrenjiAkira** [comment]
+ [ ] Slime
+ [ ] Floating Eyeball
+ [ ] Imp
