### ISSUE TITLE
Widgets don't die after being killed

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#395]
widget cards when spent are going back to backbuffer instead of dying. I probably goofed up when I refactored the card buffers

**Comment by OrenjiAkira** [comment]
I think I deserve some recognition for the title of this issue come on

**Comment by Kazuo256** [comment]
Here

![](http://i1.kym-cdn.com/photos/images/newsfeed/000/070/976/PEOPLE_DIE_IF_THEY_ARE_KILLED.jpg)
