### ISSUE TITLE
Add "gotten pack!" animation when a pack-type drop is picked up

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#433]

**Comment by rilifon** [comment]
I believe this is deprecated since packs are now drops? Someone confirm so I can close this issue

**Comment by Kazuo256** [comment]
It could just be changed to "add animation when a pack-type drop is picked up".

**Comment by Kazuo256** [comment]
Changed title to match that.

**Comment by OrenjiAkira** [comment]
It could easily be done with the number notification thing too.
