### ISSUE TITLE
Make life bar depend on the body's sprite's height

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#47]
As it is currently, the lifebar has a fixed height in relation to the tile in which its body inhabits. I believe it would be better if the lifebar was almost directly above the body's sprite, so its height in relation to the tile is variable, and would depend on the sprite's height.

**Comment by Kazuo256** [comment]
The life bar are more aligned now, but it seems the sprites themselves are not (at least the slime isn't). Maybe it is related to how this feature was being implemented?

**Comment by Kazuo256** [comment]
Anyone still working on this?
