### ISSUE TITLE
Gadgeteer Basic Pool Cards ver 1.0

### ISSUE THREAD

**Issue by rilifon** [uspgamedev/backdoor#472]
Make the following cards for the Gadgeteer background card pool

**================================**

- [ ] Jetpack
- **Widget/Suit** (Arcana)
- Buffs SPEED
- Adds tag "Float" (#460) on actor, so he can walk over "holes" and over any grounded AoE
- Has X charges. Spends one every turn

**================================**

- [ ] Radar
- **Widget/Tool** (Arcana)
- Marks the exit on the minimap (while widget is active)
- Has X charges, spends one every turn

**================================**

- [x] Goggles
- **Widget/Tool** (Corporis)
- Buffs player FoV range
- Has X charges, spends one every turn

**================================**

- [x] Wrench
- **Widget/Weapon** (Corporis)
- On use, damages nearby body (melee range) based on how many drones you have nearby
- Has X charges, spends one every use

**================================**

- [x] Blasters
- **Widget/Weapon** (Arcana)
- On use damages target body (long range)
- Has X charges, spends one every use

**================================**

- [x] Reassemble
- **Art** (Corporis)
- Choose target drone, and moves it to target valid location

**================================**

- [x] Synch
- **Art** (Arcana)
- Gives a widget to target Drone that buffs DEF

**================================**

- [ ] Drone: Ion Cannon
- **Art** (Arcana)
- Creates the body Ion Cannon on target valid position (#461)
- *Ion Cannon*:
  - Has the "on interact" (#470) widget: Has X charges, on activation spends one charge and creates a ion laser beam that shoots in opposite direction the actor has used. After use if widget has no charges, destroys the Ion Cannon body

**================================**

- [x] Drone: Turret
- **Art** (Corporis)
- Creates the body Turret on target valid position (#461)
- *Turret*:
  - Has the widget: Has X charges. On every turn, if there is a nearby non-player body (with an actor), damages it, spending one charge. If it has no charges left, destroys the Turret body

**================================**

- [ ] Drone: HealBot
- **Art** (Arcana)
- Creates the body HealBot on target valid position (#461)
- *HealBot*:
  - Has the "on interact" (#470) widget: Has X charges, on activation spends one charge and actor who activated it. After use if widget has no charges, destroys the HealBot body

**================================**

- [ ] Drone: Force Field Beacon
- **Art** (Arcana)
- Creates the body Force Field Beacon on target valid position (#461)
- *Force Field Beacon*:
  - Has the widget: Has X charges, spends one every turn. When is out of charges, destroys the Force Field Beacon body. Whenever the player enters the range of force field beacon, and the player doesn't have the "Powered Up" widget, gives the player the "Powered Up" widget. If player already had the "Powered Up" widget, set the charge for his widget to the max (Y).
  - Powered Up widget: Has Y charges, spends one every turn. Buffs actor DEF.

**================================**

- [ ] Drone: Decoy
- **Art** (Corporis)
- Creates the body Decoy on target valid position (#461)
- *Decoy*:
  - Has a widget with tag "Taunt" (#460) and X charges . Enemies will try to attack first bodies that have this tag on them. Loses one charge every turn, and when it has no charges destroys the Decoy body.

**================================**

- [x] Drone: Timer Bomb
- **Art** (Corporis)
- Creates the body Timer Bomb on target valid position (#461)
- *Timer Bomb*:
  - Has the widget : Has X charges. Every turn spends one charge. On done, widget will create an AoE (#457) that damages everybody on its range. Then it will destroy the Timer Bomb body.

**================================**

- [x] Drone: Sensor Bomb
- **Art** (Corporis)
- Creates the body Sensor Bomb on target valid position (#461)
- *Sensor Bomb*:
  - Has the widget : Has 1 charge. If any body enters the "trigger" range, it will spend one charge. On done, widget will create an AoE (#457) that damages everybody on its "explosion" range (bigger than "trigger" range). Then it will destroy the Sensor Bomb body.

**================================**
Simple cards to substitute the more complex ones:
+ [x] Flash (arcana art): stuns nearby enemies
+ [x] Jetboots (corporis widget): allows short dashes in straight lines

**Comment by Kazuo256** [comment]
Since there are many cards here that can't be currently implemented, is it ok if I make two other ones for milestone 0.1?

I was thinking of:
+ [ ] Flash (arcana art): stuns nearby enemies
+ [ ] Jetboots (arcana widget): allows short dashes in straight lines

**Comment by rilifon** [comment]
Sure!

**Comment by Kazuo256** [comment]
Closing but moved missing cards to separate issues.
