### ISSUE TITLE
Widget in actorless body can't be triggered with ON_TURN

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#474]
Because only actors have turns.

I see two main options:

1. Leave it as is and design cards around that
2. Somehow try to use the turn from the widget's owner

Option 2 could be implemented by adding a `watched_bodies` (or something) field to actors, and make them trigger these bodies with ON_TURN. Any effect that places widgets on foreign bodies should then remember to add the body to the widget owner's "watched body list".

This implementation has two issues. First, it's a pain to manage the "watched body list", since we have to remove dead bodies (and bodies that left the sector, maybe?). Second, if two different actors
put widgets on one same body, then we need to differentiate between their ON_TURN triggers (yes, you guessed it, we need to separate ON_ANY_TURN and ON_TURN).

**Comment by OrenjiAkira** [comment]
maybe we can just nuke the ON_TURN trigger and use only ON_TICK

**Comment by OrenjiAkira** [comment]
also maybe add phantom actor to actorless bodies

**Comment by Kazuo256** [comment]
> maybe we can just nuke the ON_TURN trigger and use only ON_TICK

The problem with this is that actors would then be overwhelmed with triggered effects between their
 turns. It's quite hard to balance. For instance, a regen effect couldn't ever be more than 2 or 3 hit points per TICK (that makes approximately 40-60 hit points ter TURN).

> also maybe add phantom actor to actorless bodies

That's an option, but I feel like it kills the purpose of many of our design decisions so far. I need to think of the consequences.

**Comment by Kazuo256** [comment]
Oh, another option would be to have an ON_N_TICKS trigger. No idea how to that though.

**Comment by Kazuo256** [comment]
Wait, I miscalculated.

> For instance, a regen effect couldn't ever be more than 2 or 3 hit points per TICK (that makes approximately 40-60 hit points ter TURN).

That's not true. With a speed of 4 (reasonable for starting character), an actor has a turn every **five** ticks, not twenty. So a regen effect that heals 2 hit points per TICK appear to heal 10 hit points per TURN for that actor. Still strong, but not overwhelmingly so.

This means that actually just using ON_TICK may be enough, as @OrenjiAkira first proposed. We'll just need to be slightly careful with the balancing.

**Comment by Kazuo256** [comment]
Is it ok to close this?

**Comment by OrenjiAkira** [comment]
what was decided then? for bodies we only use ON_TICK and we leave ON_TURN for actors?

**Comment by Kazuo256** [comment]
It's more like the issue wasn't even there to begin with. I just kept confusing "ticks" with "cooldown points", which caused me to think that turns only happened every 20 ticks or so, when they actually happen every 4-5 ticks.
