### ISSUE TITLE
Add highlight effect for the tile in which a body is

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#48]
Also maybe a less visible highlight in the adjacent walkable tiles, and test if these highlights work well for other bodies which are not the hero's, like monsters.

**Comment by Kazuo256** [comment]
There is a highlight now, but it also shows under monsters.

**Comment by OrenjiAkira** [comment]
I think that could be a feature so long as the monster highlight is different

**Comment by Kazuo256** [comment]
Ok then I'll change this issue description and create a new one for the different color.
