### ISSUE TITLE
Feedback for when a buffer will end

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#531]
As stated by @OrenjiAkira in #522:

> We need, regardless of everything, feedback of when drawing a card will shuffle your buffer. (Maybe drawing effects don't work when you don't have a "ready" buffer? This would facilitate managing the backbuffer/buffer state). This is important because auto-drawing messes this up completely, and it's nice knowing fast and easy when you have a backbuffer to manage or when you just need to believe in the heart of the cards to draw that one card you been waiting

**Comment by Kazuo256** [comment]
> (Maybe drawing effects don't work when you don't have a "ready" buffer? This would facilitate managing the backbuffer/buffer state)

This is the only part I'm not sure of. Why would it be easier to manage the buffer if draw effects can't draw from an "empty" frontbuffer?

**Comment by OrenjiAkira** [comment]
Because that would limit shuffling your buffer to be doable only via a maneuver, and never an ability. This makes feedback easier because it would only be necessary when you want to draw a new hand via a maneuver, and not whenever, wherever. To give proper feedback when drawing via abilities, you would also have to calculate how many cards that ability will draw, which is annoying and hard.

**Comment by Kazuo256** [comment]
Oh, I see. The problem is that it's *really* hard to implement the feedback. 

I'll try to think of a way to handle this, because not being able to draw when you do have cards to draw (in the soon-to-come backbuffer) feels rather inconsistent.

A midground solution I can come up with immediately is compromising a little. First, we make the the interface clearly show how many cards are left in the frontbuffer, specially when there are five or less (like in #124). Then, we show a very illustrative animation when you do draw the last frontbuffer card, but not before.

This is very close to what Star Realms does. [See here](https://youtu.be/l0eOvPQncMg?t=7m15s)
(couldn't find one without comments, and this is the old ugly interface of the game)

**Comment by OrenjiAkira** [comment]
I don't think this Star Realms actually achieves good feedback when it's about to shuffle anything. For one, I didn't understand what was on the player's discard pile, or even if there was any. For that matter, I couldn't see the actual deck either. Does it even shuffle things? When does the player draw cards? I just saw him play them, and when he got new cards, they just magically appeared in a seemingly random time.

But let's go back to backdoor. Whenever you hover over a card-drawing card AND it's for sure that it will shuffle your backbuffer, the interface will have to warn you somehow BEFOREHAND that THAT card will shuffle your entire buffer. Sure, you could do the math with a number somewhere in deep red at all times telling you you have only X cards left (X <= 5), but I don't think that's juicy enough. Maybe a popup balloon, saying something like "Playing this right now may shuffle your buffer!" when you hover over that card, I don't know

**Comment by Kazuo256** [comment]
Yes, as I said, this is the ugly version of Star Realm's interface. I only meant to illustrate the idea, not use their exact design as a standard. We can and we should do better. Then the question is whether simply making a better animation than them will provide enough feedback.

But, as you say, this would only communicate the player *during* the shuffle, not *beforehand*. However, even with Star Realm's ugliest UX, I never felt that necessary, while, obviously, we do feel the need for something better than Backdoor's current UX. Which is why I hypothesize that maybe we don't need to go too far. So, is it ok if we at least test a "not juicy enough" solution?

If it works, we won't have to resort to inconsistent the mechanics. If it doesn't, *then* we know we have no choice.

**Comment by Kazuo256** [comment]
Oh, right. I don't mean we shouldn't warn the player beforehand. We should. What I fear is the inconsistent mechanics part.

**Comment by OrenjiAkira** [comment]
I don't think it would make the mechanics inconsistent, but yeah, we should test something first.

**Comment by Kazuo256** [comment]
This is supposedly closed because we know show how many cards each buffer has.
