### ISSUE TITLE
Sometimes, opening packs quickly does not open them

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#555]

**Comment by Kazuo256** [comment]
Not sure, we have to test if still happens.

**Comment by OrenjiAkira** [comment]
I think I fixed it in a PR long ago.

**Comment by Kazuo256** [comment]
Can you find it?

**Comment by OrenjiAkira** [comment]
I don't even remember what was causing it. How can I possibly find it?

**Comment by Kazuo256** [comment]
I asked to know if we'd be able to link the PR here. If we can't, then oh well.

**Comment by OrenjiAkira** [comment]
I think it was solved when we changed to the maneuvers thing.
