### ISSUE TITLE
Sometimes, drawing cards crashes game because it can't find the card's color

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#558]
Can't reproduce it, but it seems to have happened mostly while playing as gadgeteer (for me)

**Comment by Kazuo256** [comment]
May also happen when you look into the backbuffer.

**Comment by OrenjiAkira** [comment]
Hasn't happened in a while. We never could reproduce it, though. It just happened randomly.

**Comment by Kazuo256** [comment]
Never seen it happen again. Since it's been a while, I think we can just close this for the time being.

**Comment by OrenjiAkira** [comment]
closing it then
