### ISSUE TITLE
Fix AI modules loadup after Godot 2.1

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#61]
Currently, the AI auto-loading is not working because instantiated scenes' children are wrongly saved in the `tscn` format. We can only fix this [when they apply this bugfix](https://github.com/godotengine/godot/issues/4579)

**Comment by OrenjiAkira** [comment]
Please explain the bug more clearly so we know not to resubmit the issue

**Comment by Kazuo256** [comment]
Done. Also, it seems the bugfix will be available on [2.0.4](https://godotengine.org/article/maintenance-release-godot-2-0-4). Let's just wait for the dust to set down a little.
