### ISSUE TITLE
Implement "drops" maybe

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#613]
"Drops" are things in tiles that when stepped on they activate an ability. They are not necessarily "dropped", as they can just "be" there. Like traps or packs or playpoints (read further).
Unlike bodies, they are _walkable_, and also _untargettable_.

The feature idea came from talking to @Kazuo256 this last reunion.
But everyone should give their two cents on it too, probably.

The whole thing started when we were talking about balancing PlayPoints, and he suggested that gathering PP should be _perpendicular_ to killing monsters. Meaning they are completely independent things. And "drops" would suffice, because we could just make collecting PP a thing you do by stepping on "drops", that can be generated in any number of ways (pre-existing, or dropped destroying bodies in general).

This would also mean refactoring packs to be drops, though that's a whole different issue.

**Comment by Kazuo256** [comment]
I've started a branch on it. Check it out, though it's still a WIP.
