### ISSUE TITLE
Avoid the use of callbacks for tweens and timers

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#621]
See if it is possible to use coroutines instead.

**Comment by OrenjiAkira** [comment]
Maybe this?
https://hump.readthedocs.io/en/latest/timer.html#Timer.script

**Comment by Kazuo256** [comment]
That seems useful.

But what this issue needs is not a yield for time, but a yield for "tween finished", "fade-in finished", etc.

**Comment by rilifon** [comment]
Every tween in hump has an optional arg to call a function the tween is
over. I think this is what you guys are looking for.
 Also tween script is only useful for the wait function, else is just a
regular tween


Em Qua, 11 de abr de 2018 21:37, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:

**Comment by OrenjiAkira** [comment]
Oh no we know about those 'on end' functions. This issue is questioning of how we can use something similar without creating lambdas over lambdas over lambdas.

Something more akin to godot's yield, I assume.

**Comment by Kazuo256** [comment]
The signals won't help because you still have to pass lambda callbacks, and that's what I'd like to get rid of. I changed the issue title to remove the confusion (sorry about that).

Interesting related read: http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/
