### ISSUE TITLE
Collect food drop when consumed PP in same spot as a drop

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#647]
When you have full PP you do not gather more PP. But if you draw a new hand you now do not have max PP. Thus it is expected that you collect any PP that is in your current tile. This does not happen, however.

**Comment by Kazuo256** [comment]
This is actually a bug. Drops should be collected at the beginning of an actor's turn.

**Comment by OrenjiAkira** [comment]
Drawing new cards does not consume turns, thus this bug. I assume

**Comment by OrenjiAkira** [comment]
closed via #650
