### ISSUE TITLE
Proposal: card-centered combat

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#795]
Backdoor is about twisting RPG/dungeon crawl/roguelike tropes into card game tropes, yet I feel our card mechanics are currently shadowed by other features or complexities. Here I propose a series of changes that should (again) make the game design more lean, but with a focus on making cards more important and fun. The idea would be to have all proposed changes together, but we can alternatively pick up only a few of them.

# Change 1: Constant damage

Not a single card game I know deals random damage predominantly (either from the MTG family of games or the deck-building archetype). I guess the fact that cards are drawn from a shuffled deck already provides enough randomness to a game, so having an additional layer of complexity by dealing random damage by default doesn't add to the chance-based fun. In fact, I fear it might only shroud things more.

With this change, all effects should usually cause a constant amount of damage (given the card's base power and the actor's attributes). We can think of cards with random damage effects, but that would be specific to those cards.

# Change 2: Defense as temporary hit points

Once we have constant damage, a new problem comes up. If your damage output is lower than your opponent's DR (damage reduction), you are simply screwed. I've actually tested it (using average damage as the constant basis): arcanists can only deal 1 damage to slimes from the get go. So, again, I looked to other card games (and related games). I realized that Hearthstone, Slay the Spire, and even D&D (5th edition) rely on temporary hit points as a means of mitigating damage.

With this change, bodies would have a pool of defense points, which absorb incoming damage. Once that pool is depleted, damages carries over to hit points as usual. The DR attribute still exists, but can only be applied while a body has defense points. For instance, if a body with 5 defense points and DR 3 takes two 6 damage attacks, first it will take 3 damage and lose 3 defense points, then take 4 damage and lose the remaining 2 defense points.

This change forces us to think of armor-flavored effects differently. An armor does not provide a passive bonus, it has to somehow provide timely defense points instead. Maybe "gain 10 defense points whenever you focus" or something. Slightly related to the following change.

# Change 3: Have EFC increase focus duration instead of reducing stamina cost

The focus system did a great job of making card hands more meaningful, but it still doesn't feel like a "card game turn", which makes cards less important. I feel like we "forget" cards exist far too easily. There is no convenient solution in other games this time, so I don't have much to go on.

The change I came up with is to stop regenerating focus whenever a card is used, and have cards cost "focus turns" instead. This way, when you begin focus, you draw 5 cards as usual, but anything you do, even playing the cards, will count towards the end of your focus (some actions more than others). The EFC attribute would now be responsible for boosting the focus duration, and stamina can be greatly simplified: we'd have at most five stamina points to spend, each food would recover exactly one point and entering focus (and drawing a hand) would always cost one point too.

We can have cards that cost zero focus (e.g. equipping something) and effects that restore or prolong the focus (e.g. a condition that makes your next 3 moves not consume focus). I'd also suggest adding a "focus only" flag to conditions and/or equipment, so we can, for instance, avoid buying cards with Seedling Sap outside of focus.

**Comment by rilifon** [comment]
I like the ideia of fixed damage and armour. I vote we test them.

About focus, I like the way you are heading. For me it made using cards
more of a frustration to spend them once in a while not to lose my hand.
This way of all cards spending focus could prove fun, but then I would
suggest reducing (or plain removing which I prefer to test first) walking
spending focus.
Also, cards with fixed focus costs could make some choices of picking more
interesting (picking several high cost strong cards could give and
advantage, but you risk having a hand that you can't fully cast).
Here I give once again the ideia that buying a new have discounts the
amount of cards you already have.





Em Sáb, 4 de ago de 2018 19:54, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:

**Comment by Kazuo256** [comment]
@rilifon I had a few typos in the text, so to be sure take another look at the last item to see if it still makes sense to you.

**Comment by Kazuo256** [comment]
I'm doing some experiments here, and the greatest problem I'm facing is that using focus as a resource for playing cards effectively makes most actions have two separate costs: time and focus.

Is that too complex? Can you envision the differences between slow actions and focus-heavy actions? Is that interesting?

**Comment by rilifon** [comment]
I think it goes against the less-is-more dilema, since both resources are
very similar, but have completely different results. This could be very
confusing for the player...

Maybe we scratch focus and think of another way to engage the player into
using his hand?

Em Sáb, 4 de ago de 2018 23:40, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:

**Comment by Kazuo256** [comment]
We could go back to how focus was at first. Instead of counting turns, it counted absolute in-game time. This way, card's time cost can be the only cost.

On the other hand, we changed it to the current way for a reason. Was it because binding focus to time made it even harder to use the cards? I don't remember.

**Comment by Kazuo256** [comment]
Alright, this is what I have now.

EFC goes back to determining how much stamina it costs to start focus. Focus depletes every TURN, but does not recover when cards are used or drawn. Also, you cannot activate widgets outside focus (maybe I'll make this a per-widget option).

Card costs are simpler again (or at least no more complex than they were before), and the fact that you need to be focused to use even basic attacks draws more attention to cards, I hope.

**Comment by Kazuo256** [comment]
If you guys want, check the PR out. It's still WIP but you can already experiment with the changes.
