### ISSUE TITLE
Smoother movement

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#796]
One of the complaints about Backdoor on Glitch Mundo was that you could tap right twice but move only one tile.

Should we queue movement inputs?

**Comment by rilifon** [comment]
I don't like the idea of accidently pressing too much movements inputs and
the game locks my actions. But I understand the complaint and we should
consider it.
My suggestion, make something Slay the Spire did: in the options menu, have
a toggle option named "fast game" or something like that, that improves
overall speed of game. This could include way faster animation for walking,
enemies and fast-forwarding/skipping most effects.
For first players, they can play the game "slower", better understanding
what is happening and be graced by our amazing visual effects.
For experienced players they can toggle this option and play the game at a
faster pace.

Em Sáb, 4 de ago de 2018 20:15, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:

**Comment by OrenjiAkira** [comment]
Part of the problem is efficiency. When there are too many monsters, their AI takes some time to calculate everything.

**Comment by rilifon** [comment]
I believe the movement of the monsters that take most of the time no?
Because the AI should be really fast (unless we are doing something really
inneficient).
I think the slowest part of our update is the fov algorithms, and I think
we can improve them a bit to cost less processing time when the time comes.

Em Sáb, 4 de ago de 2018 20:42, W. Akira Mizutani <notifications@github.com>
escreveu:

**Comment by Kazuo256** [comment]
How about this:

If you hold down a direction button (or axis), you "keep moving" in that direction the same way auto-walk would. That is, if there's anything "important" in view, you won't move more than one tile even if you hold down, and you stop moving if were before.

**Comment by rilifon** [comment]
Sounds good

Em Sáb, 4 de ago de 2018 21:00, Wilson Kazuo Mizutani <
notifications@github.com> escreveu:

**Comment by rilifon** [comment]
This was closed after #606

**Comment by Kazuo256** [comment]
#606 was just long walk, but not the feature of moving by holding a directional button as stated in this issue. Even then, auto-longwalk might not fix the problem of staggered movement in the game.
