### ISSUE TITLE
Initial sector guides

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#818]
NPCs that explain game mechanics. This issue is for us to list each one we want.

**Comment by rilifon** [comment]
**Initial wise-person** - Mentions the objective of the game, in clear terms, using a dialogue image to actually show what a Vanth's Fruits should look like.

Draft dialogue: "Today is the fateful day. You remember what you are supposed to do right? Find and bring back one of Vanth's Fruits, located in one of the edges of our world, Vanthen'eah."

**Comment by rilifon** [comment]
**Group 1 of NPCs, a group of kids** - Jealous your task, they mention you'll have to face monsters and use cards to defeat them. Also talk about consuming and levelling up.

Kid 1 draft dialogue: _"Hey mister, you're the one that's bringing prosperity back to us right? I heard it's very dangerous out there, full of monsters! You be careful mister!"_
_Kid 2 draft dialogue_: "

**Comment by rilifon** [comment]
**Group 2 of NPCs, two adults chatting** - They teach you about focus, pp and how to open and use cards,.

Adult 1 draft dialogue: _"Are well rested for the journey? Remember that get a new hand of cards you need to hold X, but that costs you Play Points. You can get some of my food if you need to replenish some."_
Adult 2 draft dialogue: _"Don't forget that your hand is active while your Focus lasts! When its over, you'll discard your whole hand..."_

**Comment by rilifon** [comment]
**Group 3 of NPCs, two old people** - Teach you about packs and consuming. In front of them there is a pack the player can pick up, with a pre-defined content, and a ritual site.

Old person 1 draft dialogue: _"Here is a pack for you, young-one. You can look at your collected packs and open them if you hold X. Its important to choose which cards to consume and which to add to your buffer."_

Old person 2 draft dialogue: _"Consuming is important to improve your abilities. How much you improve in each attribute is based on the type of cards you most use. You can consume a few cards in this resting place next to me"_

**Comment by rilifon** [comment]
**Group 4 of NPCs, two adults** - Teach you about widgets and using them

Adult 1 draft dialogue: _"There are two types of cards, art and widgets. Widgets are different since you'll get a lasting effect or equipment that can have an amount of charges related to them."_

Adult 2 draft dialogue: _"Some widgets give you an activated ability. You can toggle them using X and use them with Y. Remember that if your Focus runs out, you'll lose all active widgets!"_

**Comment by rilifon** [comment]
**Final NPC** - Stays near the exit, teachs you about interacting with the map and the hint button.

Draft dialogue: _"To interact with something, stay above while you are not Focused, and press X. Remember you can hold X if you forget some essencial commands... Good luck adventurer."_
