### ISSUE TITLE
Sprites for buffers

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#843]
Should show if buffers is ending.

**Comment by rilifon** [comment]
![card_buffer](https://user-images.githubusercontent.com/3944304/44236874-05434700-a19e-11e8-9aee-5ec2efd482a5.png)
How is this for a buffer icon

**Comment by rilifon** [comment]
![back_buffer](https://user-images.githubusercontent.com/3944304/44238317-b698ab80-a1a3-11e8-99b1-7cd245cd0307.png)
Image for buffer. For back-buffer, @Kazuo256 suggested we try to setColor as to modulate the borders.
If the rest think the image is fine, I'll close the issue
