### ISSUE TITLE
Rendered FOV shows one more tile beyond the actual logic FOV

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#879]

**Comment by rilifon** [comment]
I tested here, and currently with FOV = n, the player can see n tiles away. FOV = 0, the player would only see itself. If we change the logic, FOV 0 the player wouldn't see a thing, and discussing with @Kazuo256 we think the way it is now makes more sense. Do you agree @OrenjiAkira? If so,  close the issue.

**Comment by OrenjiAkira** [comment]
logically yes the player can only see up to n tiles of distance. however, the map tiles are rendered one tile beyond the logical FOV, and it causes confusion when your map isnt updated according the walls you have already seen

**Comment by rilifon** [comment]
Hmm you mean the "half-tile" that appears teasing the tiles beyond your FOV, that is your complaint?

**Comment by OrenjiAkira** [comment]
yes

**Comment by OrenjiAkira** [comment]
please note that the issue clearly states that the problem is the rendere fov
