### ISSUE TITLE
Make objects for WidgetIcons

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#883]
For #881 and #882, we need the widget icons that appear on the actor HUD to be actual objects that hold their own position.

This might require some state-keeping from another object, which knows what widgets are placed where, because, some icon positions are dynamic (e.g. you lose a condition and all others conditions shift left).

**Comment by rilifon** [comment]
Method needed to implement: 
getPoint() - Returns current center position of the widget on-screen
