### ISSUE TITLE
Show monster's name with their sprite

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#97]
Also add names to the monsters themselves.

**Comment by Kazuo256** [comment]
What about showing it above them? After all, the life bar is above them.

**Comment by Kazuo256** [comment]
Bump.

**Comment by OrenjiAkira** [comment]
I was working on it, I think? I think I got side tracked. Anyway, it should be easily done. The bodyview already uses info from a meta file that comes with the sprite. It should load a name from there. All that is left is making the name visible.

**Comment by Kazuo256** [comment]
What I wanted to know was about where the name should go, actually =D

**Comment by rafaeljpc** [comment]
It's mandatory to show a enemy name?
Maybe a card that do that..... only boss I think is useful to know the name

**Comment by Kazuo256** [comment]
I think it gives somes substance to the lore. But I see it would be a rather minor feature in the game. Maybe we can postpone this issue to prioritize other things.

**Comment by OrenjiAkira** [comment]
I think it is very important for the monsters to have names. But, as I think further on the subject, I also think that they don't have to be visible along with the lifebar. I intended to make a hud that shows info on actions and monsters and such. Maybe it could, for example, show on the monster's status window.

**Comment by Kazuo256** [comment]
Closed via #382
