### ISSUE TITLE
Missing method wrap for Source:setLooping()

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#978]
![bug](https://user-images.githubusercontent.com/645222/49961432-ccbc3b80-fef9-11e8-935a-ef4e25747988.png)

**Comment by OrenjiAkira** [comment]
setLooping is a method of Source. if we wrapped that class we have to make sure the methods are still accessible

**Comment by Kazuo256** [comment]
Alright, updated title
